version: '3.8'
services:
  dev-db:
    image: postgres:16
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 222
      POSTGRES_DB: test-DB-nest-t
    networks:
      - freecodecamp
networks:
  freecodecamp:
